### ISSUE TITLE
MIM fails with an 500 internal error on every requests

### ISSUE THREAD

**Issue by Ruffio** [lithnet/resourcemanagement-webservice#11]
Hi.

I have installed and configured this REST API and can get the help page without any issues:
![1](https://user-images.githubusercontent.com/1877612/38558381-2a40cefc-3cd0-11e8-8293-88b38b62da50.png)

I have made the below sample console to test:
![2](https://user-images.githubusercontent.com/1877612/38558399-3e1b0b40-3cd0-11e8-9a48-9cc4c6a2c32b.png)

However I always get this error:
![3](https://user-images.githubusercontent.com/1877612/38558419-59b5442e-3cd0-11e8-887a-7dc57016d761.png)

In the Eventview\Application I see this error every time:
![4](https://user-images.githubusercontent.com/1877612/38558450-7a155592-3cd0-11e8-976a-e1db79e3d029.png)

If I change the credentials in the console, then I get an erro about invalid credentials, so I know that my credentials are correct. What can be the issue? The MIM 2016 installation is working without any issues but this :-(

What can be the issue? I can't find any other places to look for error messages. Any ideas?

**Comment by ryannewington** [comment]
Hi @Ruffio 

A few things to note

1. The URL you are calling is not a valid REST endpoint without having additional parameters. Have a look at the [wiki page](https://github.com/lithnet/resourcemanagement-webservice/wiki/Get-a-resource-(v2)) and include either an ID or a attribute/value pair do the API knows what resource to get

2. The sharepoint foundation errors you are seeing are not related. They are from the portal, whereas this API calls directly into the MIM service, which does not use sharepoint.

3. If you are developing from C#, I suggest using the resource management .NET client https://github.com/lithnet/resourcemanagement-client, rather than the rest API. It wraps all the API calls directly to the MIM service and is much easier to use from C# code.

4. A great tool for testing REST APIs is [postman](https://www.getpostman.com/). Handles all the headers, encoding, etc for you. 

Let me know how you go

Ryan

**Comment by ryannewington** [comment]
@Ruffio did you need any further help with this?

**Comment by Ruffio** [comment]
I have switched to the C# Client and it is working perfectly :-)
