### ISSUE TITLE
Capture more error codes

### ISSUE THREAD

**Issue by bryanjager** [lithnet/resourcemanagement-webservice#14]
I am getting a mix of JSON and HTML pages as errors.  I found that the following codes are not being caught.  Can you please catch the following error codes and return JSON?

- 401
- 501-504

Thank you very much!

**Comment by bryanjager** [comment]
Can 200 be captured as well to return JSON?

**Comment by ryannewington** [comment]
Hi Bryan,

It is a bit tricky because of the type of interaction that WCF REST has with IIS. I don't have the ability to intercept errors that occur outside of my code, which result in default IIS pages. 

I do have future plans to re-write the project as a newer WebAPI project, which support this sort of thing a lot better. However, I don't have any concrete dates on this. It's a big job and I have a very full plate at the moment.

If you've got specific exceptions from the MIM resource side that you believe aren't returning correctly, then I can look to fix that, but other errors are out of my control.

Ryan

**Comment by bryanjager** [comment]
Thanks for the reply. I see that IIS can capture the above errors. Someone else mentioned that I write some custom code to return the appropriate JSON error on the appropriate IIS error redirect. Looks like I have to do that for now until you support these error codes.  Do you have any other workarounds that byou can suggest? 

Thankfor all you do on this project. 😀
