### ISSUE TITLE
Error when accessing the rest api 

### ISSUE THREAD

**Issue by arthurabreu1** [lithnet/resourcemanagement-webservice#20]
Hi Ryan,

I followed all the installation instructions but am getting the error below when trying to access the REST API with the following addresses:

https://servername:4431/
https://servername:4431/v1/help
https://servername:4431/v1/resources
https://servername:4431/v2/help
https://servername:4431/v2/resources

**Server Error in '/' Application.

Parser Error 
  Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

 Parser Error Message: Could not load type 'Lithnet.ResourceManagement.WebService.Global'.

Source Error: 

Line 1:  <%@ Application Codebehind="Global.asax.cs" Inherits="Lithnet.ResourceManagement.WebService.Global" Language="C#" %>

  

 Source File:  /global.asax    Line:  1 

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3282.0** 

I have tried to change Codebehind to Codefile in Global.asax as suggested in some forums but that only generated more errors. 

Any ideas?

Thanks

**Comment by ryannewington** [comment]
Hi @arthurabreu1,

This sort of message is typically caused by one or more IIS features being missing. Have you double checked the [installation guide](https://github.com/lithnet/resourcemanagement-webservice/wiki/Installing-the-web-service) to make sure all components have been installed.

Definitely don't change the contents of any code files.

- IIS 7.5 or higher with the following features installed
- ASP.NET
- .NET Extensibility
- ISAPI Extensions
- ISAPI Filters
- Basic Authentication
- .NET Framework 4.6.1
