### ISSUE TITLE
SOAP call to FIM?

### ISSUE THREAD

**Issue by kongarasri** [lithnet/resourcemanagement-webservice#21]
Hi Ryan,

Any plans on providing documentation for a SOAP call to FIM? I was trying to do a SOAP call to FIM, any idea how to get the service endpoint?

Thanks

**Comment by ryannewington** [comment]
Hi,

No, there are no plans to provide documentation for making raw soap calls. That's something you can approach Microsoft for.

Why do you need to talk soap though? You have this solution if you need to make calls via a Web service, or you can use https://github.com/lithnet/resourcemanagement-client to use straight from your.net code.

The soap interface is a pain, which is why I provided these alternative solutions.

If there is something my libraries can't do, let me know and I may be able to add the functionality.

Ryan

**Comment by kongarasri** [comment]
I agree with you SOAP is a pain and we are using the REST API services you provided. But, we have some customizations to the user data in FIM and which can be queried only from the metaverse. We had a requirement for one of the PowerShell scripts we are working on and it needs to query the user details in the metaverse for that we need to do a SOAP call.

**Comment by ryannewington** [comment]
There is no soap api for the metaverse.

The soap api provided by fim is for the fim service only. Even with a custom schema, you can manage all object types and attributes using the lithnet rest api, power shell, or . net client library.

You can use lithnet miis-powershell to query the metaverse. However this only works from the sync server box itself. Fim does not provide an interface to query the metaverse remotely. Your best bet is to push the attributes you want to see into the fim service and manage them from there.
