### ISSUE TITLE
Can we deploy this as subsite in MIM Portal site

### ISSUE THREAD

**Issue by sivabalaguru** [lithnet/resourcemanagement-webservice#24]
I would like to use the existing MIM Portal setup with minimal changes. I would have to use same ports 80 and 443 for this web service on the servers where MIM Portal is installed.

Can we deploy this as a subsite in MIM Portal like https://idweb.contoso.com/identitywebservice/v1
?

I did tried this. But it gave me error while consuming the webservice. I was able to browse the help page.

**Comment by KentNordstrom** [comment]
I typically use the same instance of IIS as MIM Portal, but use a separate WebSite and HostName for the REST API. I reuse the same Application Pool Identity since then Kerberos Delegation to FIMService is already in place. This in my opinion is the minimal impact setup to use.

Then the URLs would be like https://mimportal.company.com for MIM Portal and like https://mimrest.company.com for REST API.

**Comment by ryannewington** [comment]
@sivabalaguru, Kent is correct. It will need to run in a separate web site, but you can use a host name binding to run it on the same IP and port. It's not support to run it within the FIM Portal web application itself.

**Comment by sivabalaguru** [comment]
Thanks Kent. Deploying in the same website didn't work.
