### ISSUE TITLE
Integrated Pipeline

### ISSUE THREAD

**Issue by PeterNorris2** [lithnet/resourcemanagement-webservice#33]
Is it possible to run the Lithnet API using the Integrated Pipeline in IIS? If not what would need changing to allow that to happen?

**Comment by ryannewington** [comment]
@PeterNorris2 classic mode is needed for impersonation to work correctly to allow the credentials of the caller of the API to be passed back to the MIM service. Otherwise the MIM service sees all requests coming from the service account running the REST API, and you have no control over authorization.

**Comment by PeterNorris2** [comment]
Thanks for a very swift answer. Is this restriction to do with WCF? I have written purely Integrated Pipeline Web APIs that succeed in doing Kerberos to a back-end. The Kerberos config was a pain as I remember.
